### ISSUE TITLE
Making Mellon and Keycloak work in a Containerized environment

### ISSUE THREAD

**Issue by mckenziec** [latchset/mod_auth_mellon#15]
Hi. I've been struggling to get Mellon + Apache Httpd working as a reverse proxy against a Keycloak SAML IdP in a Docker setup, where only Httpd + Mellon is publicly accessible. The reverse proxy points to Camunda and Eramba containers. I intended to add Elasticsearch in there as well, but I'm having a hell of a time getting Mellon and Keycloak happy.

To this end I'm kind of desperately seeing if the issue might be Mellon vs Keycloak.

First, as a bit of preamble that'll lead to my issue. I've had a tough time retrieving a suitable idp_metadata.xml from Keycloak because it's Realm SAML definition point basically writes the Location related URLs relative to how the requesting browser called it. e.g. if I open my browser and connect to http://proxy.demo/auth/realms/myrealm/protocol/saml/descriptor, the entityID and Locations will be from host/port http://proxy.demo:

```
<EntitiesDescriptor Name="urn:keycloak" xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
                                       xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
       <EntityDescriptor entityID="http://proxy.demo/auth/realms/myrealm">
...
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://proxy.demo/auth/realms/myrealm/protocol/saml"/>
```

Here's a sample using `curl -s -k -o /etc/httpd/saml2/idp_metadata2.xml http://127.0.0.1:8082/auth/realms/myrealm/protocol/saml/descriptor` (Note that this is the official Keycloak container and I exposed port 8080 and 8082):

```
<EntitiesDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" Name="urn:keycloak">
<EntityDescriptor entityID="http://127.0.0.1:8082/auth/realms/myrealm">
...
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://127.0.0.1:8082/auth/realms/myrealm/protocol/saml"/>
```

When I went back to Mellon and tried accessing a protected reverse URL, I would get redirected to the **Locations** written in the idp_metadata.xml. Of course from the user browser, those addresses are not reachable. e.g. http://sso:8080 is a URL that the Mellon container can reach and get the idp_metadata.xml, BUT its not something the user browser can reach.

I was a little confused that Mellon with a Httpd reverse proxy setup wouldn't proxy the auth requests, instead it looked like Mellon was redirecting the user browser directly to a resource end point only accessible from behind the proxy.

So in the interested of keeping my sanity I rigged up a way to satisfy the browser redirection. I just allowed the Httpd proxy to allow /auth to go to my Keycloak service. Then I grabbed the IdP SAML definition using the publicly accessible URL. e.g. http://proxy.demo/

The resulting idp_metadata.xml had the correct URLs in it. I considered rewriting the idp_metadata.xml, but I would have to first prove this setup works at all. If you have any tips on how to deal with this, I'm all ears. It'll be a common challenge with containerized SAML architectures.

Now when my use browser accesses a protected URL (e.g. http://proxy.demo/camunda), Mellon will direct me to a publicly accessible URL (I shortened the SAMLRequest and Signature values): 
```
http://proxy.demo/auth/realms/myrealm/protocol/saml?SAMLRequest=hZJfa...k3&amp;RelayState=http%3A%2F%2Fproxy.demo%2Fcamunda&amp;SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&amp;Signature=lMJd4mzGJP9%2FXxT...SWon5lgMYxrkkQ%3D%3D
```
However Keycloak displays an "Invalid requester" error in the browser. From the Keycloak logs show the following exception ("Invalid query param signature"):
```
00:11:13,206 ERROR [org.keycloak.protocol.saml.SamlService] (default task-2) request validation failed: org.keycloak.common.VerificationException: org.keycloak.common.VerificationException: Invalid query param signature
	at org.keycloak.keycloak-services@8.0.0//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:169)
	at org.keycloak.keycloak-services@8.0.0//org.keycloak.protocol.saml.SamlService$RedirectBindingProtocol.verifySignature(SamlService.java:557)
	at org.keycloak.keycloak-services@8.0.0//org.keycloak.protocol.saml.SamlService$BindingProtocol.handleSamlRequest(SamlService.java:250)
```

I'm trying desperately to figure out what the "Invalid query param signature" could mean! The Keycloak forum has been quiet. 

Keycloak seems to be unhappy with the SAML Signature Request Key. It is able to located a valid public key for validation, but then when it tried to validate the Signature using the identified SigAlg (https://www.w3.org/2001/04/) it failed with "Invalid query param signature":

https://github.com/keycloak/keycloak/blob/d39dfd86888d292ebdafd6b5b98be2436b64846c/services/src/main/java/org/keycloak/protocol/saml/SamlProtocolUtils.java#L134

Do you have any tips? I'm not looking for you to support Keycloak, but any suggestions or clues would really be helpful. 

I can attach anything that might help. e.g. copies of my Mellon SP files, Keycloak IDP file, my httpd.conf, etc...

If it helps I'm running Keycloak 8.0, and mod_auth_mellon 0.14.0 on httpd 2.4.6-90 in a Centos 7.7 image. I thought to stick with whatever came with Centos 7 to be safe, but I'm not married to it.

Thank you/

**Comment by xpuska513** [comment]
You can try to generate new saml keys in your client, then export the new client configuration from keycloak and update existing mellon metadata(keys,certs etc.) with a new one from keycloak. I had the same issue
